README.md
While working on the transpilation branch, I figured I'd also copy over other analogous parts of cypress-vue-unit-test, since it's a bit more fleshed out.
=> Readme consistency with cypress-vue-unit-test

README.md, cypress/integration/transpiled-spec.js, cypress/plugins/index.js, package.json, src/transpiled.jsx
Adds a test confirming that transpiling works, and readme instructions for enabling transpiling.
=> Transpiling

README.md, cypress/plugins/index.js, package-lock.json, package.json
=> Upgrade webpack preprocessor

.gitignore, README.md, circle.yml, cypress/integration/error-boundary-spec.js, package-lock.json, package.json, plugins/cra-v3/file-preprocessor.js, plugins/cra-v3/index.js
So you don't have to configure transpile. Configuration file does this for plugins
```json
{
"pluginsFile": "node_modules/cypress-react-unit-test/plugins/cra-v3"
}
```
=> feat: re-use bundler from CRA v3

lib/index.ts
=> fix: better error message on missing support file

cypress/component/basic/use-render/my-component-spec.js, cypress/component/basic/use-render/my-component.jsx
- closes #172 
The example is the same as the user-provided code sample but with fixed syntax error
=> add issue example but fixed

README.md, cypress/component/advanced/testing-lib-example/testing-lib-spec.js, cypress/plugins/index.js, cypress/support/index.js, package-lock.json, package.json
just added a note about speed for #156
=> fix: add note about speed

examples/webpack-options/.npmrc, examples/webpack-options/cypress.json, examples/webpack-options/cypress/component/Test.cy-spec.js, examples/webpack-options/cypress/integration/cy-spec.js, examples/webpack-options/cypress/plugins/index.js, examples/webpack-options/cypress/support/index.js, examples/webpack-options/package.json, plugins/cra-v3/file-preprocessor.js
=> fix: use default webpack options

cypress/component/advanced/timers/README.md, cypress/component/advanced/timers/card-spec.js, cypress/component/advanced/timers/card-without-effect-spec.js, cypress/component/advanced/timers/card.jsx, lib/index.ts
=> fix: add delay to let hooks run

circle.yml
- Percy tests are running again
- closes #216
=> use base image 12.16.2 to run Percy tests

README.md, circle.yml, examples/sass-and-ts/cypress.json, examples/sass-and-ts/package.json, examples/sass-and-ts/webpack.config.js, package-lock.json, package.json, plugins/load-webpack/index.js
- closes #141 
- upgrades https://github.com/bahmutov/find-webpack/issues/7 to find Babel loader rules in more situations
- tested using `examples/sass-and-ts` folder
=> feat: insert istanbul babel plugin in more situations

circle.yml, examples/react-scripts-folder/cypress/plugins/index.js, examples/react-scripts-folder/package.json, examples/react-scripts/cypress/plugins/index.js, examples/react-scripts/package.json, examples/tailwind/cypress.json, examples/tailwind/cypress/plugins/index.js, examples/tailwind/package.json, examples/visual-sudoku/README.md, examples/visual-sudoku/cypress/plugins/index.js, examples/visual-testing-with-applitools/README.md, examples/visual-testing-with-applitools/cypress/plugins/index.js, examples/visual-testing-with-happo/README.md, examples/visual-testing-with-happo/cypress/plugins/index.js, examples/visual-testing-with-percy/README.md, examples/visual-testing-with-percy/cypress/plugins/index.js, examples/webpack-options/cypress/component/Test.cy-spec.js, examples/webpack-options/cypress/component/Test.js, examples/webpack-options/cypress/plugins/index.js, examples/webpack-options/cypress/support/index.js, examples/webpack-options/package.json
- closes #254
- updated code coverage for all examples
=> Check code coverage for all examples

README.md, cypress/component/basic/no-visit/spec.js, cypress/integration/integration tests/integration-spec.js, lib/hooks.ts
- closes #286
- closes #282 
- added tests
=> feat: throw an error if a component spec calls cy.visit

examples/sass-and-ts/README.md
If you like the way it looks I'll do the same for the other examples. Let me know if you want changes.
=> Updated the readme for the sass-and-ts example

plugins/cra-v3/file-preprocessor.js
=> fix: transpile integration folder too

circle.yml, cypress/component/advanced/react-book-example/src/Note.spec.js, cypress/component/advanced/tutorial/square-spec.js, cypress/component/advanced/use-local-storage/README.md, cypress/component/basic/react-book-by-chris-noring/README.md, package-lock.json, package.json
- closes #314
- warns if there `.only` test pre-commit
- stops the Git push if there is `.only` test
=> stop exclusive tests

circle.yml
=> Check Applitools env variable before running tests

README.md, cypress/component/advanced/mocking-imports/PizzaProps.js, cypress/component/advanced/mocking-imports/PizzaProps.spec.js, cypress/component/advanced/mocking-imports/README.md, cypress/component/advanced/mocking-imports/RemotePizza.js, cypress/component/advanced/mocking-imports/RemotePizza.spec.js, cypress/component/advanced/mocking-imports/services.js, cypress/component/advanced/mocking-imports/spec.js, examples/react-scripts/cypress.json, examples/react-scripts/package.json, examples/react-scripts/src/RemotePizza.cy-spec.js, examples/react-scripts/src/RemotePizza.js, examples/react-scripts/src/services.js
- closes #358
- problem was `<component>.defaultProps` intermediate object
=> add mocking defaultProps method example

lib/index.ts
Remove some of `@ts-ignore`. Properly infer some values that were inferred as `any`
=> chore: Improve typings

examples/nextjs/README.md, examples/nextjs/cypress.json, examples/nextjs/cypress/components/HelloWorld.spec.jsx, examples/nextjs/cypress/components/Search.spec.jsx, examples/nextjs/package.json, package-lock.json, package.json, plugins/next/file-preprocessor.js
=> fix: collect code coverage for Next.js components

README.md, cypress/component/basic/before-hook/README.md, cypress/component/basic/before-hook/spec.js
just to make sure the component stays there
=> add example of using before hook to mount the component

README.md, cypress/component/advanced/window-env/App.js, cypress/component/advanced/window-env/README.md, cypress/component/advanced/window-env/spec.js
=> add example with setting window._env property

circle.yml, examples/a11y/cypress.json, examples/a11y/package.json, examples/tailwind/package.json, package-lock.json, package.json
Following https://glebbahmutov.com/blog/testing-pyramids/
=> Move a11y example to install this library from TGZ file

circle.yml, examples/react-scripts-folder/package.json, examples/react-scripts/package.json
- move examples/react-scripts and react-scripts-folder
=> move dependencies for react-scripts examples

circle.yml, examples/react-scripts/package.json, examples/react-scripts/src/add.js, examples/react-scripts/src/dynamic-import.cy-spec.js, package-lock.json
Trying to have more examples with lazy imports
secondary: getting hook error trying to run `examples/react-scripts` Pizza spec locally
=> add another dynamic import test to react-scripts

circle.yml, examples/sass-and-ts/package.json, examples/sass-and-ts/webpack.config.js
=> Move sass example dependencies

circle.yml, examples/webpack-file/package.json
=> move dependencies for webpack-file example

circle.yml, examples/nextjs/package.json, examples/webpack-options/package.json
=> Move nextjs dependencies

circle.yml, examples/snapshots/package.json, examples/using-babel-typescript/package.json, examples/using-babel/package.json, examples/visual-sudoku/package.json, package-lock.json, package.json
=> Move more example dependencies

examples/nextjs/components/UsingHelper.jsx, examples/nextjs/components/helpers/hello-world.js, examples/nextjs/components/helpers/index.js, examples/nextjs/cypress/components/UsingHelper.spec.jsx, examples/nextjs/package.json, plugins/next/file-preprocessor.js
=> fix: set Next.js pages to load from /pages folder

circle.yml, cypress/component/advanced/mocking-axios/1-users.spec.js, plugins/next/file-preprocessor.js
- finishes work for #513 
- related to the conversation in https://github.com/bahmutov/cypress-react-unit-test/pull/518
cc @larrifax
=> fix: use pages or src/pages folder for Next.js
